// Copyright (c) 2026 FiveOS. Licensed under the GNU GPLv3. See LICENSE.
// https://github.com/w3bportal/FiveOS

using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;

namespace FiveOS.Services;

/// <summary>
/// Writes drop-in catalog snippets for the five housing scripts FiveOS
/// targets out of the box. The streamed-asset pack is identical across
/// every target (one <c>stream/</c> dir + one merged ytyp) — the only
/// thing that varies is the format of the per-script "furniture catalog"
/// table that surfaces the prop in the script's in-game furniture menu.
///
/// Layout produced under <c>&lt;pack&gt;/housing/</c>:
///
///   ps-housing.snippet.lua          paste into shared/config.lua
///   qbx_properties.snippet.lua      paste into config/client.lua
///   loaf_housing.snippet.lua        paste into furniture.lua
///   qs-housing.import.json          bulk-import via Quasar's housing creator
///   nolag_properties/&lt;pack&gt;.lua    drop into nolag_properties/custom/furniture/
///   catalog.json                    universal machine-readable form
///
/// Three of the five scripts (ps-housing, qbx_properties, loaf_housing)
/// preview props by spawning them live in-game during placement — no
/// thumbnails needed. The remaining two (qs-housing, nolag_properties)
/// ship their own greenscreen generators. Nothing here writes images.
/// </summary>
public static class HousingCatalogEmitter
{
    public sealed record MappedEntry(PropPackEntry Entry, string ArchetypeName);

    public static void Emit(
        string resourceDir,
        string packDisplayName,
        string packSafeName,
        IReadOnlyList<MappedEntry> entries)
    {
        if (entries.Count == 0) return;

        var housingDir = Path.Combine(resourceDir, "housing");
        Directory.CreateDirectory(housingDir);

        WritePsHousing(housingDir, packDisplayName, packSafeName, entries);
        WriteQbxProperties(housingDir, packDisplayName, packSafeName, entries);
        WriteLoafHousing(housingDir, packDisplayName, packSafeName, entries);
        WriteQsHousingJson(housingDir, packDisplayName, packSafeName, entries);
        WriteNolagProperties(housingDir, packDisplayName, packSafeName, entries);
        WriteUniversalCatalog(housingDir, packDisplayName, packSafeName, entries);
    }

    // ───────────────────────── ps-housing ─────────────────────────
    //
    // shared/config.lua append. Category list is fixed: Prerequisites,
    // Couches, Chairs, Storage, Electronics, Beds, Lighthing (sic — the
    // typo IS the actual key in the upstream script, do not "fix" it).

    private static readonly Dictionary<string, string> PsCategoryMap = new(StringComparer.OrdinalIgnoreCase)
    {
        [HousingCategory.Couches]     = "Couches",
        [HousingCategory.Chairs]      = "Chairs",
        [HousingCategory.Tables]      = "Chairs",      // ps has no Tables bucket
        [HousingCategory.Beds]        = "Beds",
        [HousingCategory.Storage]     = "Storage",
        [HousingCategory.Electronics] = "Electronics",
        [HousingCategory.Lighting]    = "Lighthing",   // upstream typo, preserved
        [HousingCategory.Decorations] = "Chairs",      // closest "misc" bucket
    };

    private static void WritePsHousing(string housingDir, string packDisplay, string packSafe, IReadOnlyList<MappedEntry> entries)
    {
        var sb = new StringBuilder();
        sb.AppendLine("-- ps-housing furniture catalog generated by FiveOS");
        sb.AppendLine($"-- Pack: {packDisplay}");
        sb.AppendLine("--");
        sb.AppendLine("-- HOW TO USE:");
        sb.AppendLine("--   Open ps-housing/shared/config.lua, find the Config.Furnitures table,");
        sb.AppendLine("--   and append the entries below into the matching category's items list.");
        sb.AppendLine("--   ps-housing's categories are fixed — adding a new top-level category");
        sb.AppendLine("--   to the table also works.");
        sb.AppendLine();

        // Group by ps-housing's native category names so consumers can paste
        // each block into the matching items{} table without re-sorting.
        var grouped = entries
            .GroupBy(e => MapPsCategory(e.Entry.Category))
            .OrderBy(g => g.Key, StringComparer.Ordinal);

        foreach (var group in grouped)
        {
            sb.AppendLine($"-- ── {group.Key} ──");
            foreach (var e in group)
                sb.AppendLine(BuildPsLine(e));
            sb.AppendLine();
        }

        File.WriteAllText(Path.Combine(housingDir, "ps-housing.snippet.lua"),
            sb.ToString(), new UTF8Encoding(false));
    }

    private static string BuildPsLine(MappedEntry m)
    {
        var parts = new List<string>
        {
            $"[\"object\"] = \"{m.ArchetypeName}\"",
            $"[\"price\"] = {m.Entry.Price}",
            $"[\"label\"] = \"{EscapeLua(m.Entry.Label)}\"",
        };
        switch (m.Entry.Type)
        {
            case FurnitureType.Storage:
                parts.Add("[\"type\"] = \"storage\"");
                parts.Add("[\"max\"] = 2");
                break;
            case FurnitureType.Wardrobe:
                parts.Add("[\"type\"] = \"clothing\"");
                parts.Add("[\"max\"] = 2");
                break;
        }
        return "    { " + string.Join(", ", parts) + " },";
    }

    private static string MapPsCategory(string canonical)
        => PsCategoryMap.TryGetValue(canonical ?? "", out var mapped) ? mapped : "Chairs";

    // ───────────────────────── qbx_properties ─────────────────────────
    //
    // config/client.lua append. Only four built-in buckets: lighting,
    // couches, tables, beds. Anything outside those collapses into
    // "couches" — qbx users can add a `decorations = { … }` key if they
    // want a separate bucket, but it's a one-time config edit.

    private static readonly Dictionary<string, string> QbxCategoryMap = new(StringComparer.OrdinalIgnoreCase)
    {
        [HousingCategory.Couches]     = "couches",
        [HousingCategory.Chairs]      = "couches",
        [HousingCategory.Tables]      = "tables",
        [HousingCategory.Beds]        = "beds",
        [HousingCategory.Storage]     = "couches",
        [HousingCategory.Electronics] = "couches",
        [HousingCategory.Lighting]    = "lighting",
        [HousingCategory.Decorations] = "couches",
    };

    private static void WriteQbxProperties(string housingDir, string packDisplay, string packSafe, IReadOnlyList<MappedEntry> entries)
    {
        var sb = new StringBuilder();
        sb.AppendLine("-- qbx_properties furniture catalog generated by FiveOS");
        sb.AppendLine($"-- Pack: {packDisplay}");
        sb.AppendLine("--");
        sb.AppendLine("-- HOW TO USE:");
        sb.AppendLine("--   Open qbx_properties/config/client.lua, find the `furniture` table,");
        sb.AppendLine("--   and append the entries below to the matching category arrays.");
        sb.AppendLine("--   qbx_properties has four built-in categories: lighting / couches /");
        sb.AppendLine("--   tables / beds — anything else falls into couches by default.");
        sb.AppendLine();

        var grouped = entries
            .GroupBy(e => MapQbxCategory(e.Entry.Category))
            .OrderBy(g => g.Key, StringComparer.Ordinal);

        foreach (var group in grouped)
        {
            sb.AppendLine($"-- ── {group.Key} ──");
            foreach (var e in group)
                sb.AppendLine($"    {{ object = '{e.ArchetypeName}', label = '{EscapeLuaSingle(e.Entry.Label)}' }},");
            sb.AppendLine();
        }

        File.WriteAllText(Path.Combine(housingDir, "qbx_properties.snippet.lua"),
            sb.ToString(), new UTF8Encoding(false));
    }

    private static string MapQbxCategory(string canonical)
        => QbxCategoryMap.TryGetValue(canonical ?? "", out var mapped) ? mapped : "couches";

    // ───────────────────────── loaf_housing ─────────────────────────
    //
    // furniture.lua append. loaf is config-driven — users add new
    // categories freely. Emit lowercased canonical names; user can rename
    // post-hoc if they want them merged into an existing category.

    private static void WriteLoafHousing(string housingDir, string packDisplay, string packSafe, IReadOnlyList<MappedEntry> entries)
    {
        var sb = new StringBuilder();
        sb.AppendLine("-- loaf_housing furniture catalog generated by FiveOS");
        sb.AppendLine($"-- Pack: {packDisplay}");
        sb.AppendLine("--");
        sb.AppendLine("-- HOW TO USE:");
        sb.AppendLine("--   Open loaf_housing/furniture.lua. Make sure each category below is");
        sb.AppendLine("--   declared in Config.Categories, then append each block to the matching");
        sb.AppendLine("--   Config.Furniture[<category>] table.");
        sb.AppendLine();

        var grouped = entries
            .GroupBy(e => (e.Entry.Category ?? HousingCategory.Decorations).ToLowerInvariant())
            .OrderBy(g => g.Key, StringComparer.Ordinal)
            .ToList();

        // Emit a Config.Categories hint block so users can copy declared
        // categories straight into their config.
        sb.AppendLine("-- Add to Config.Categories if not already present:");
        foreach (var g in grouped)
            sb.AppendLine($"--   {{'{g.Key}', '{Capitalize(g.Key)}'}},");
        sb.AppendLine();

        foreach (var group in grouped)
        {
            sb.AppendLine($"Config.Furniture['{group.Key}'] = Config.Furniture['{group.Key}'] or {{}}");
            foreach (var e in group)
            {
                sb.AppendLine(
                    $"table.insert(Config.Furniture['{group.Key}'], " +
                    $"{{ object = '{e.ArchetypeName}', label = '{EscapeLuaSingle(e.Entry.Label)}', price = {e.Entry.Price} }})");
            }
            sb.AppendLine();
        }

        File.WriteAllText(Path.Combine(housingDir, "loaf_housing.snippet.lua"),
            sb.ToString(), new UTF8Encoding(false));
    }

    // ───────────────────────── qs-housing ─────────────────────────
    //
    // Quasar's housing creator has a bulk-import path that takes a JSON
    // array of furniture rows. Quasar generates thumbnails in-game via
    // their own tool, so no image paths are emitted.

    private static void WriteQsHousingJson(string housingDir, string packDisplay, string packSafe, IReadOnlyList<MappedEntry> entries)
    {
        var rows = entries.Select(e => new
        {
            model    = e.ArchetypeName,
            label    = e.Entry.Label,
            price    = e.Entry.Price,
            category = (e.Entry.Category ?? HousingCategory.Decorations).ToLowerInvariant(),
            type     = e.Entry.Type switch
            {
                FurnitureType.Storage  => "stash",
                FurnitureType.Wardrobe => "wardrobe",
                _                      => null,
            },
        }).ToList();

        var json = JsonSerializer.Serialize(new
        {
            pack    = packDisplay,
            resource = packSafe,
            generated = DateTime.UtcNow.ToString("o", CultureInfo.InvariantCulture),
            items   = rows,
        }, new JsonSerializerOptions { WriteIndented = true });

        File.WriteAllText(Path.Combine(housingDir, "qs-housing.import.json"),
            json, new UTF8Encoding(false));
    }

    // ───────────────────────── nolag_properties ─────────────────────────
    //
    // TeamsGG's NoLag has an explicit "drop-in" folder:
    // nolag_properties/custom/furniture/. Each file is a Lua module that
    // returns nothing (it just appends into the global FurnitureConfig.Furniture
    // table that nolag loads at start). One file per pack keeps adds/removes
    // a single delete-the-file operation.

    private static void WriteNolagProperties(string housingDir, string packDisplay, string packSafe, IReadOnlyList<MappedEntry> entries)
    {
        var subdir = Path.Combine(housingDir, "nolag_properties");
        Directory.CreateDirectory(subdir);

        var sb = new StringBuilder();
        sb.AppendLine($"-- nolag_properties furniture pack generated by FiveOS");
        sb.AppendLine($"-- Pack: {packDisplay}");
        sb.AppendLine("--");
        sb.AppendLine("-- HOW TO USE:");
        sb.AppendLine("--   Drop this file into nolag_properties/custom/furniture/ — it self-registers");
        sb.AppendLine("--   into FurnitureConfig.Furniture on resource start.");
        sb.AppendLine();
        sb.AppendLine("FurnitureConfig = FurnitureConfig or {}");
        sb.AppendLine("FurnitureConfig.Furniture = FurnitureConfig.Furniture or {}");
        sb.AppendLine();

        var grouped = entries
            .GroupBy(e => (e.Entry.Category ?? HousingCategory.Decorations).ToLowerInvariant())
            .OrderBy(g => g.Key, StringComparer.Ordinal);

        foreach (var group in grouped)
        {
            sb.AppendLine($"FurnitureConfig.Furniture['{group.Key}'] = FurnitureConfig.Furniture['{group.Key}'] or {{");
            sb.AppendLine($"    label = '{EscapeLuaSingle(Capitalize(group.Key))}',");
            sb.AppendLine($"    items = {{}},");
            sb.AppendLine("}");
            sb.AppendLine($"FurnitureConfig.Furniture['{group.Key}'].items = FurnitureConfig.Furniture['{group.Key}'].items or {{}}");
            foreach (var e in group)
            {
                var parts = new List<string>
                {
                    $"object = '{e.ArchetypeName}'",
                    $"price = {e.Entry.Price}",
                    $"label = '{EscapeLuaSingle(e.Entry.Label)}'",
                };
                if (e.Entry.Type == FurnitureType.Storage)  parts.Add("type = 'stash'");
                if (e.Entry.Type == FurnitureType.Wardrobe) parts.Add("type = 'wardrobe'");
                sb.AppendLine(
                    $"table.insert(FurnitureConfig.Furniture['{group.Key}'].items, " +
                    $"{{ {string.Join(", ", parts)} }})");
            }
            sb.AppendLine();
        }

        File.WriteAllText(Path.Combine(subdir, packSafe + ".lua"),
            sb.ToString(), new UTF8Encoding(false));
    }

    // ───────────────────────── universal catalog.json ─────────────────────────
    //
    // Single source-of-truth dump in case a downstream tool (a "FiveOS
    // furniture bridge" resource, future housing-script support, server
    // owners writing their own glue) wants to read the pack programmatically
    // without parsing five different Lua dialects.

    private static void WriteUniversalCatalog(string housingDir, string packDisplay, string packSafe, IReadOnlyList<MappedEntry> entries)
    {
        var doc = new
        {
            schemaVersion = 1,
            generator     = "FiveOS",
            generated     = DateTime.UtcNow.ToString("o", CultureInfo.InvariantCulture),
            pack          = new
            {
                name     = packDisplay,
                resource = packSafe,
            },
            items = entries.Select(e => new
            {
                archetype = e.ArchetypeName,
                label     = e.Entry.Label,
                category  = e.Entry.Category,
                price     = e.Entry.Price,
                type      = e.Entry.Type switch
                {
                    FurnitureType.Storage  => "storage",
                    FurnitureType.Wardrobe => "wardrobe",
                    _                      => "decoration",
                },
                sizeBytes = e.Entry.TotalBytes,
            }).ToList(),
        };

        var json = JsonSerializer.Serialize(doc, new JsonSerializerOptions { WriteIndented = true });
        File.WriteAllText(Path.Combine(housingDir, "catalog.json"),
            json, new UTF8Encoding(false));
    }

    // ───────────────────────── helpers ─────────────────────────

    private static string EscapeLua(string s)
        => (s ?? "").Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static string EscapeLuaSingle(string s)
        => (s ?? "").Replace("\\", "\\\\").Replace("'", "\\'");

    private static string Capitalize(string s)
        => string.IsNullOrEmpty(s) ? s : char.ToUpperInvariant(s[0]) + s[1..];
}
