// Copyright (c) 2026 FiveOS. All rights reserved.
// https://github.com/w3bportal/FiveOS

using System.Collections.Generic;
using System.IO;
using System.Text;

namespace FiveOS.Services;

/// <summary>
/// Standalone FiveM resource for a SYNCED emote — two players or a whole
/// group, no rpemotes required. Ships the streamed .ycd plus a client/server
/// script pair implementing a slot-based flow: the initiator runs
/// /&lt;name&gt; near N other players → each gets a chat prompt → everyone
/// answers "/&lt;name&gt; accept" → once ALL slots are filled the server
/// broadcasts a single start event, every accepted player teleports to their
/// authored offset (same semantics rpemotes uses:
/// GetOffsetFromEntityInWorldCoords(side, front, height), heading
/// subtracted) and the whole formation plays the clip simultaneously.
/// Nothing plays until everyone is in — that is the sync guarantee.
/// </summary>
public static class SyncFiveMResourceBuilder
{
    /// <summary>One partner slot: offsets relative to the initiator.</summary>
    public readonly record struct Slot(double Front, double Side, double Height, double Heading);

    public static void BuildFolder(
        string folderPath, string emoteName, string displayName, byte[] ycdBytes,
        IReadOnlyList<Slot> slots)
    {
        Directory.CreateDirectory(folderPath);
        Directory.CreateDirectory(Path.Combine(folderPath, "stream"));

        File.WriteAllBytes(Path.Combine(folderPath, "stream", emoteName + ".ycd"), ycdBytes);

        string F(double v) => v.ToString("0.###", System.Globalization.CultureInfo.InvariantCulture);
        int need = slots.Count;
        string kind = need == 1 ? "synced two-player emote" : $"synced group emote ({need + 1} players)";

        // The description lands inside a single-quoted Lua string in a file
        // FXServer executes — a stray backslash ("dance \o/") is a Lua lexer
        // error that kills the WHOLE resource at server start, so strip every
        // character that can break or escape the literal.
        var safeName = displayName
            .Replace("\\", "").Replace("'", "").Replace("\r", " ").Replace("\n", " ");

        var fx = new StringBuilder();
        fx.AppendLine($"-- Generated by FiveOS — {kind}");
        fx.AppendLine();
        fx.AppendLine("fx_version 'cerulean'");
        fx.AppendLine("game 'gta5'");
        fx.AppendLine($"description '{safeName} (synced emote)'");
        fx.AppendLine();
        fx.AppendLine("client_script 'client.lua'");
        fx.AppendLine("server_script 'server.lua'");
        File.WriteAllText(Path.Combine(folderPath, "fxmanifest.lua"), fx.ToString());

        var cl = new StringBuilder();
        cl.AppendLine($"-- Generated by FiveOS — {kind}");
        cl.AppendLine($"local EMOTE = '{emoteName}'");
        cl.AppendLine($"local DICT, CLIP = '{emoteName}', '{emoteName}'");
        cl.AppendLine("-- One entry per partner slot: side (right), front (ahead), height (up),");
        cl.AppendLine("-- heading (subtracted from the initiator's; 180 = face them).");
        cl.AppendLine("local OFFSETS = {");
        foreach (var s in slots)
            cl.AppendLine($"    vector4({F(s.Side)}, {F(s.Front)}, {F(s.Height)}, {F(s.Heading)}),");
        cl.AppendLine("}");
        cl.AppendLine("local NEED = #OFFSETS");
        cl.AppendLine("local pendingFrom = nil");
        cl.AppendLine();
        cl.AppendLine("local function msg(text)");
        cl.AppendLine("    TriggerEvent('chat:addMessage', { args = { '^3' .. EMOTE, text } })");
        cl.AppendLine("end");
        cl.AppendLine();
        cl.AppendLine("local function playOn(ped)");
        cl.AppendLine("    RequestAnimDict(DICT)");
        cl.AppendLine("    local deadline = GetGameTimer() + 5000");
        cl.AppendLine("    while not HasAnimDictLoaded(DICT) and GetGameTimer() < deadline do Wait(10) end");
        cl.AppendLine("    if not HasAnimDictLoaded(DICT) then msg('Animation failed to load.') return end");
        cl.AppendLine("    TaskPlayAnim(ped, DICT, CLIP, 8.0, -8.0, -1, 1, 0.0, false, false, false)");
        cl.AppendLine("end");
        cl.AppendLine();
        cl.AppendLine("RegisterCommand(EMOTE, function(_, args)");
        cl.AppendLine("    if args[1] == 'accept' then");
        cl.AppendLine("        if not pendingFrom then msg('No pending request.') return end");
        cl.AppendLine("        TriggerServerEvent('fiveos_sync:accept:' .. EMOTE, pendingFrom)");
        cl.AppendLine("        pendingFrom = nil");
        cl.AppendLine("        msg(NEED == 1 and 'Accepted.' or 'Accepted — waiting for the rest of the group…')");
        cl.AppendLine("        return");
        cl.AppendLine("    end");
        cl.AppendLine("    if args[1] == 'cancel' then");
        cl.AppendLine("        -- Works both ways: an initiator cancels their session, an invitee");
        cl.AppendLine("        -- declines (which cancels the whole all-or-nothing session).");
        cl.AppendLine("        TriggerServerEvent('fiveos_sync:cancel:' .. EMOTE, pendingFrom)");
        cl.AppendLine("        pendingFrom = nil");
        cl.AppendLine("        msg('Cancelled.')");
        cl.AppendLine("        return");
        cl.AppendLine("    end");
        cl.AppendLine("    if args[1] == 'stop' then");
        cl.AppendLine("        ClearPedTasks(PlayerPedId())");
        cl.AppendLine("        msg('Stopped.')");
        cl.AppendLine("        return");
        cl.AppendLine("    end");
        cl.AppendLine("    -- Initiate: the NEED nearest players within 5 m, closest first.");
        cl.AppendLine("    local mc = GetEntityCoords(PlayerPedId())");
        cl.AppendLine("    local cand = {}");
        cl.AppendLine("    for _, pid in ipairs(GetActivePlayers()) do");
        cl.AppendLine("        if pid ~= PlayerId() then");
        cl.AppendLine("            local d = #(GetEntityCoords(GetPlayerPed(pid)) - mc)");
        cl.AppendLine("            if d <= 5.0 then cand[#cand + 1] = { pid = pid, d = d } end");
        cl.AppendLine("        end");
        cl.AppendLine("    end");
        cl.AppendLine("    table.sort(cand, function(a, b) return a.d < b.d end)");
        cl.AppendLine("    if #cand < NEED then");
        cl.AppendLine("        msg(('Need %d player%s within 5 m — found %d.'):format(NEED, NEED == 1 and '' or 's', #cand))");
        cl.AppendLine("        return");
        cl.AppendLine("    end");
        cl.AppendLine("    local ids = {}");
        cl.AppendLine("    for i = 1, NEED do ids[i] = GetPlayerServerId(cand[i].pid) end");
        cl.AppendLine("    TriggerServerEvent('fiveos_sync:request:' .. EMOTE, ids)");
        cl.AppendLine("    msg(NEED == 1 and 'Request sent…' or ('Invites sent to %d players…'):format(NEED))");
        cl.AppendLine("end, false)");
        cl.AppendLine();
        cl.AppendLine("RegisterNetEvent('fiveos_sync:prompt:' .. EMOTE, function(fromId)");
        cl.AppendLine("    pendingFrom = fromId");
        cl.AppendLine("    msg(('%s wants to %s with you — type /%s accept'):format(");
        cl.AppendLine("        GetPlayerName(GetPlayerFromServerId(fromId)) or 'Someone', EMOTE, EMOTE))");
        cl.AppendLine("end)");
        cl.AppendLine();
        cl.AppendLine("RegisterNetEvent('fiveos_sync:progress:' .. EMOTE, function(count, need)");
        cl.AppendLine("    msg(('%d/%d accepted…'):format(count, need))");
        cl.AppendLine("end)");
        cl.AppendLine();
        cl.AppendLine("RegisterNetEvent('fiveos_sync:cancelled:' .. EMOTE, function(reason)");
        cl.AppendLine("    pendingFrom = nil");
        cl.AppendLine("    msg(reason or 'Cancelled.')");
        cl.AppendLine("end)");
        cl.AppendLine();
        cl.AppendLine("-- slot 0 = the initiator (stays put); slots 1..NEED teleport to OFFSETS[slot].");
        cl.AppendLine("-- Everyone receives this in the same server broadcast, so the whole");
        cl.AppendLine("-- formation snaps into place and starts the clip together.");
        cl.AppendLine("RegisterNetEvent('fiveos_sync:start:' .. EMOTE, function(initiatorId, slot)");
        cl.AppendLine("    local me = PlayerPedId()");
        cl.AppendLine("    if slot > 0 then");
        cl.AppendLine("        local off = OFFSETS[slot]");
        cl.AppendLine("        -- GetPlayerFromServerId is -1 for a departed initiator, and");
        cl.AppendLine("        -- GetPlayerPed(-1) is the LOCAL ped — guard both.");
        cl.AppendLine("        local ip = GetPlayerFromServerId(initiatorId)");
        cl.AppendLine("        local other = ip ~= -1 and GetPlayerPed(ip) or 0");
        cl.AppendLine("        if off and other ~= 0 then");
        cl.AppendLine("            local pos = GetOffsetFromEntityInWorldCoords(other, off.x, off.y, off.z)");
        cl.AppendLine("            SetEntityHeading(me, GetEntityHeading(other) - off.w)");
        cl.AppendLine("            SetEntityCoordsNoOffset(me, pos.x, pos.y, pos.z, false, false, false)");
        cl.AppendLine("        end");
        cl.AppendLine("    end");
        cl.AppendLine("    playOn(me)");
        cl.AppendLine("    msg(('Playing — /%s stop to end it.'):format(EMOTE))");
        cl.AppendLine("end)");
        File.WriteAllText(Path.Combine(folderPath, "client.lua"), cl.ToString());

        var sv = new StringBuilder();
        sv.AppendLine($"-- Generated by FiveOS — {kind} (session relay)");
        sv.AppendLine($"local EMOTE = '{emoteName}'");
        sv.AppendLine($"local NEED = {need}");
        sv.AppendLine("local TIMEOUT_MS = 30000");
        sv.AppendLine("local tokenCounter = 0");
        sv.AppendLine("local sessions = {} -- [initiatorId] = { token, invited = {id -> slot}, accepted = {}, count }");
        sv.AppendLine();
        sv.AppendLine("local function cancelSession(initiator, reason)");
        sv.AppendLine("    local s = sessions[initiator]");
        sv.AppendLine("    if not s then return end");
        sv.AppendLine("    sessions[initiator] = nil");
        sv.AppendLine("    TriggerClientEvent('fiveos_sync:cancelled:' .. EMOTE, initiator, reason)");
        sv.AppendLine("    for id in pairs(s.invited) do");
        sv.AppendLine("        TriggerClientEvent('fiveos_sync:cancelled:' .. EMOTE, id, reason)");
        sv.AppendLine("    end");
        sv.AppendLine("end");
        sv.AppendLine();
        sv.AppendLine("RegisterNetEvent('fiveos_sync:request:' .. EMOTE, function(targetIds)");
        sv.AppendLine("    local initiator = source");
        sv.AppendLine("    if type(targetIds) ~= 'table' then return end");
        sv.AppendLine("    if sessions[initiator] then cancelSession(initiator, 'Request replaced.') end");
        sv.AppendLine("    tokenCounter = tokenCounter + 1");
        sv.AppendLine("    local s = { token = tokenCounter, invited = {}, accepted = {}, count = 0 }");
        sv.AppendLine("    local n = 0");
        sv.AppendLine("    for _, id in ipairs(targetIds) do");
        sv.AppendLine("        if n >= NEED then break end");
        sv.AppendLine("        id = tonumber(id)");
        sv.AppendLine("        if id and id ~= initiator and not s.invited[id] then");
        sv.AppendLine("            n = n + 1");
        sv.AppendLine("            s.invited[id] = n -- slot index into the client's OFFSETS");
        sv.AppendLine("        end");
        sv.AppendLine("    end");
        sv.AppendLine("    if n < NEED then return end");
        sv.AppendLine("    sessions[initiator] = s");
        sv.AppendLine("    for id in pairs(s.invited) do");
        sv.AppendLine("        TriggerClientEvent('fiveos_sync:prompt:' .. EMOTE, id, initiator)");
        sv.AppendLine("    end");
        sv.AppendLine("    local token = s.token");
        sv.AppendLine("    SetTimeout(TIMEOUT_MS, function()");
        sv.AppendLine("        local cur = sessions[initiator]");
        sv.AppendLine("        if cur and cur.token == token then cancelSession(initiator, 'Request timed out.') end");
        sv.AppendLine("    end)");
        sv.AppendLine("end)");
        sv.AppendLine();
        sv.AppendLine("RegisterNetEvent('fiveos_sync:accept:' .. EMOTE, function(initiatorId)");
        sv.AppendLine("    initiatorId = tonumber(initiatorId)");
        sv.AppendLine("    local s = initiatorId and sessions[initiatorId] or nil");
        sv.AppendLine("    if not s then");
        sv.AppendLine("        -- Dead/replaced session: tell the acceptor instead of silently");
        sv.AppendLine("        -- swallowing the command for the rest of the timeout window.");
        sv.AppendLine("        TriggerClientEvent('fiveos_sync:cancelled:' .. EMOTE, source, 'That request is no longer active.')");
        sv.AppendLine("        return");
        sv.AppendLine("    end");
        sv.AppendLine("    local slot = s.invited[source]");
        sv.AppendLine("    if not slot or s.accepted[source] then return end");
        sv.AppendLine("    s.accepted[source] = true");
        sv.AppendLine("    s.count = s.count + 1");
        sv.AppendLine("    if s.count < NEED then");
        sv.AppendLine("        TriggerClientEvent('fiveos_sync:progress:' .. EMOTE, initiatorId, s.count, NEED)");
        sv.AppendLine("        return");
        sv.AppendLine("    end");
        sv.AppendLine("    -- Everyone is in: one broadcast, whole formation starts together.");
        sv.AppendLine("    sessions[initiatorId] = nil");
        sv.AppendLine("    TriggerClientEvent('fiveos_sync:start:' .. EMOTE, initiatorId, initiatorId, 0)");
        sv.AppendLine("    for id, sl in pairs(s.invited) do");
        sv.AppendLine("        TriggerClientEvent('fiveos_sync:start:' .. EMOTE, id, initiatorId, sl)");
        sv.AppendLine("    end");
        sv.AppendLine("end)");
        sv.AppendLine();
        sv.AppendLine("RegisterNetEvent('fiveos_sync:cancel:' .. EMOTE, function(fromInitiatorId)");
        sv.AppendLine("    -- Initiator: cancel own session. Invitee: decline — the formation is");
        sv.AppendLine("    -- all-or-nothing, so a decline cancels that whole session with notice");
        sv.AppendLine("    -- instead of leaving everyone to silently wait out the timeout.");
        sv.AppendLine("    if sessions[source] then");
        sv.AppendLine("        cancelSession(source, 'Cancelled by the initiator.')");
        sv.AppendLine("        return");
        sv.AppendLine("    end");
        sv.AppendLine("    local init = tonumber(fromInitiatorId)");
        sv.AppendLine("    local s = init and sessions[init] or nil");
        sv.AppendLine("    if s and s.invited[source] then");
        sv.AppendLine("        cancelSession(init, ('%s declined.'):format(GetPlayerName(source) or 'A player'))");
        sv.AppendLine("    end");
        sv.AppendLine("end)");
        File.WriteAllText(Path.Combine(folderPath, "server.lua"), sv.ToString());

        var rd = new StringBuilder();
        rd.AppendLine($"# {displayName} — {kind} (generated by FiveOS)");
        rd.AppendLine();
        rd.AppendLine("1. Drop this folder into your server's `resources/` directory.");
        rd.AppendLine($"2. Add `ensure {Path.GetFileName(folderPath)}` to server.cfg (or `refresh` + `start`).");
        rd.AppendLine(need == 1
            ? $"3. In game: stand near another player and run `/{emoteName}`."
            : $"3. In game: stand near {need} other players and run `/{emoteName}` — the {need} nearest get invited.");
        rd.AppendLine($"4. Each invited player confirms with `/{emoteName} accept`.");
        rd.AppendLine(need == 1
            ? "5. On accept they snap to position and both of you play in sync."
            : "5. Only when EVERYONE has accepted does the group snap into formation and play in sync (30 s timeout).");
        rd.AppendLine($"6. `/{emoteName} cancel` cancels a pending request (initiator) or declines an invite.");
        rd.AppendLine($"7. `/{emoteName} stop` ends the emote for yourself once it is playing.");
        File.WriteAllText(Path.Combine(folderPath, "README.md"), rd.ToString());
    }
}
