using System.IO;
using System.Text;

namespace FiveOS.Services;

public static class VehiclePackTemplate
{
    public static string Create(string parentFolder, string resourceName)
    {
        var name = Sanitize(resourceName);
        if (name.Length == 0) name = "car_pack";
        var outDir = Path.Combine(parentFolder, name);
        Directory.CreateDirectory(outDir);
        Directory.CreateDirectory(Path.Combine(outDir, "stream"));
        Directory.CreateDirectory(Path.Combine(outDir, "data"));
        Directory.CreateDirectory(Path.Combine(outDir, "audio", "sfx"));

        File.WriteAllText(Path.Combine(outDir, "stream", ".gitkeep"), "");
        File.WriteAllText(
            Path.Combine(outDir, "data", "vehicles.meta"),
            VehicleMetaFormService.MinimalStub(VehicleMetaKind.Vehicles));
        File.WriteAllText(
            Path.Combine(outDir, "data", "handling.meta"),
            VehicleMetaFormService.MinimalStub(VehicleMetaKind.Handling));
        File.WriteAllText(
            Path.Combine(outDir, "data", "carvariations.meta"),
            VehicleMetaFormService.MinimalStub(VehicleMetaKind.Carvariations));
        File.WriteAllText(
            Path.Combine(outDir, "data", "carcols.meta"),
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
            "<CVehicleModelInfoVarGlobal>\n  <Kits />\n  <Lights />\n  <Sirens />\n</CVehicleModelInfoVarGlobal>\n");

        var fx = new StringBuilder();
        fx.AppendLine("-- Generated by FiveOS (empty vehicle pack template)");
        fx.AppendLine();
        fx.AppendLine("fx_version 'cerulean'");
        fx.AppendLine("game 'gta5'");
        fx.AppendLine();
        fx.AppendLine("files {");
        fx.AppendLine("    'data/vehicles.meta',");
        fx.AppendLine("    'data/handling.meta',");
        fx.AppendLine("    'data/carvariations.meta',");
        fx.AppendLine("    'data/carcols.meta',");
        fx.AppendLine("}");
        fx.AppendLine();
        fx.AppendLine("data_file 'VEHICLE_METADATA_FILE' 'data/vehicles.meta'");
        fx.AppendLine("data_file 'HANDLING_FILE' 'data/handling.meta'");
        fx.AppendLine("data_file 'VEHICLE_VARIATION_FILE' 'data/carvariations.meta'");
        fx.AppendLine("data_file 'CARCOLS_FILE' 'data/carcols.meta'");
        fx.AppendLine();
        fx.AppendLine("client_script 'vehicle_names.lua'");
        File.WriteAllText(Path.Combine(outDir, "fxmanifest.lua"), fx.ToString());

        var lua = new StringBuilder();
        lua.AppendLine("Citizen.CreateThread(function()");
        lua.AppendLine("end)");
        File.WriteAllText(Path.Combine(outDir, "vehicle_names.lua"), lua.ToString());

        return outDir;
    }

    private static string Sanitize(string raw)
    {
        var sb = new StringBuilder();
        foreach (var c in (raw ?? "").Trim())
        {
            if (char.IsLetterOrDigit(c) || c is '_' or '-') sb.Append(char.ToLowerInvariant(c));
            else if (char.IsWhiteSpace(c) || c == ' ') sb.Append('_');
        }
        return sb.ToString().Trim('_');
    }
}
